import type { CSSProperties, ReactNode, SVGProps } from "react";
import {
  LOGO_PIECES,
  LOGO_VIEWBOX,
  type LogoPieceId,
} from "@/components/services/logoGeometry";

/**
 * THE ONE REAL-LOGO SVG MARK (shared by the Services Hub and the hero).
 *
 * The five pieces are inline paths traced from the owner's own artwork (see
 * `components/services/logoGeometry.ts`, generated by `scripts/trace-logo.mjs`;
 * measured silhouette IoU 0.9984). They are NEVER primitives — no capsules, no
 * rounded rectangles. This component exists so the Hub and the hero cannot
 * drift apart: one geometry, one gradient set, one `data-logo-piece` contract.
 *
 * The component renders the `<svg>` element itself. Callers own layout,
 * animation classes and pointer handlers through the callback props, so the Hub
 * keeps its `hub__logo` contract byte-for-byte and the hero gets the same mark
 * with its own explode vars.
 *
 * `idPrefix` keeps the gradient ids unique when more than one mark is mounted
 * on the same page (the hero and the Hub are both on `/`).
 */
export interface LogoMarkSvgProps {
  /** Class on the root `<svg>`. */
  className?: string;
  /** Prefix for the gradient ids — required when two marks share a document. */
  idPrefix?: string;
  /** ViewBox override (defaults to the traced source viewBox). */
  viewBox?: string;
  /** Extra `<svg>` attributes (aria-hidden, focusable, pointer handlers…). */
  svgProps?: SVGProps<SVGSVGElement>;
  /** Class on each `<g data-logo-piece>`. */
  pieceClassName?: (piece: LogoPieceId, index: number) => string | undefined;
  /** Inline style on each `<g data-logo-piece>` (explode custom properties). */
  pieceStyle?: (piece: LogoPieceId, index: number) => CSSProperties | undefined;
  /** Extra attributes/handlers on each `<g data-logo-piece>`. */
  pieceProps?: (piece: LogoPieceId, index: number) => SVGProps<SVGGElement>;
  /** Extra layers appended after the pieces (anchors, glow, …). */
  children?: ReactNode;
}

export function logoGradientIdFor(piece: LogoPieceId, idPrefix = ""): string {
  return `${idPrefix}jazari-logo-grad-${piece}`;
}

export function LogoMarkSvg({
  className,
  idPrefix = "",
  viewBox = LOGO_VIEWBOX,
  svgProps,
  pieceClassName,
  pieceStyle,
  pieceProps,
  children,
}: LogoMarkSvgProps) {
  return (
    <svg className={className} viewBox={viewBox} {...svgProps}>
      <defs>
        {LOGO_PIECES.map((piece) => (
          <linearGradient
            key={piece.id}
            id={logoGradientIdFor(piece.id, idPrefix)}
            gradientUnits="userSpaceOnUse"
            x1={piece.gradient.x1}
            y1={piece.gradient.y1}
            x2={piece.gradient.x2}
            y2={piece.gradient.y2}
          >
            {piece.gradient.stops.map((stop, index) => (
              <stop key={index} offset={stop.offset} stopColor={stop.color} />
            ))}
          </linearGradient>
        ))}
      </defs>
      {LOGO_PIECES.map((piece, index) => (
        <g
          key={piece.id}
          data-logo-piece={piece.id}
          className={pieceClassName?.(piece.id, index)}
          style={pieceStyle?.(piece.id, index)}
          {...pieceProps?.(piece.id, index)}
        >
          <path d={piece.d} fill={`url(#${logoGradientIdFor(piece.id, idPrefix)})`} />
        </g>
      ))}
      {children}
    </svg>
  );
}

export default LogoMarkSvg;
