"use client";

import { useCallback, useMemo, useRef, useState } from "react";
import { api } from "@/lib/api";
import { useApiData } from "@/hooks/useApiData";
import { useReducedMotion } from "@/hooks/useReducedMotion";
import { Reveal } from "@/components/motion/Reveal";
import { SectionIndex } from "@/components/layout/SectionIndex";
import { CircuitTrace } from "@/components/layout/CircuitTrace";
import { iconRegistry, InfoIcon, type IconName } from "@/components/icons";
import {
  LOGO_PIECES,
  LOGO_VIEWBOX,
  logoGradientId,
  type LogoPieceId,
} from "@/components/services/logoGeometry";
import {
  HUB_DESIGN,
  HUB_GRID_UNIT,
  HUB_PIECES,
  HUB_REFERENCE_WIDTH,
  HUB_SLOT_PIECES,
  cardSlotStyle,
  wirePath,
} from "@/components/services/hubLayout";
import type { Service } from "@/types/api";

/**
 * OUR SERVICES HUB — the signature interaction, rebuilt on the real artwork.
 *
 * LOGO GEOMETRY
 * The five pieces are inline SVG paths traced from the owner's own logo
 * (`frontend/public/Main Logo.png` by way of `Real Logo.png`). They are NOT
 * capsules, rounded rectangles or any other primitives — see
 * `components/services/logoGeometry.ts` (generated by `scripts/trace-logo.mjs`)
 * and the measured silhouette IoU recorded in `LOGO_TRACE_META`. The assembled
 * SVG reproduces the source artwork's straight edges, real corner curvature,
 * real angles and the narrow gaps between bands.
 *
 * INTERACTION
 * At rest the mark is assembled. Hover, keyboard focus or tap explodes the five
 * groups along their own outward directions with a 40-60 ms stagger; Escape
 * reassembles. Hovering or focusing a card highlights its piece and brightens
 * its trace, and hovering a piece highlights the matching card — both directions
 * are driven by stable `data-logo-piece` / `data-hub-card` identities, never by
 * DOM traversal.
 *
 * DATA
 * Business content always comes from `GET /api/services`. The up-to-five
 * featured services are the ones flagged with a `hubSlot`, ordered by slot and
 * mapped through `HUB_SLOT_PIECES`; nothing is hardcoded and nothing is
 * shuffled. The service list is always present in the DOM, so the section is
 * fully readable without JavaScript and remains meaningful under reduced motion.
 */

interface HubCard {
  service: Service;
  piece: LogoPieceId;
  slot: number;
}

/**
 * Per-piece CSS custom properties consumed by the hub styles.
 *
 * The travel values are SVG user units in the logo's 4096 viewBox. They are
 * emitted with an explicit `px` unit because the CSS `transform` property
 * rejects unitless lengths — `translate(-95, -115)` is invalid CSS and would
 * silently leave every piece unmoved. For SVG elements `1px` is exactly one
 * user unit, so the geometry is unchanged by adding the unit.
 */
function pieceVars(piece: LogoPieceId, index: number): React.CSSProperties {
  const { tx, ty, rot } = HUB_PIECES[piece].explode;
  return {
    "--i": index,
    "--tx": `${tx}px`,
    "--ty": `${ty}px`,
    "--rot": `${rot}deg`,
  } as React.CSSProperties;
}

export function ServicesHub() {
  const { data } = useApiData(() => api.services(), "services");
  const reducedMotion = useReducedMotion();

  const hubRef = useRef<HTMLDivElement>(null);
  const [open, setOpen] = useState(false);
  const [active, setActive] = useState<LogoPieceId | null>(null);

  // Under reduced motion the diagram is permanently in its static exploded
  // state, so `open` must be truthful for aria-expanded from the first render.
  const exploded = reducedMotion ? true : open;

  /**
   * Featured services: those flagged with a `hubSlot`, ordered by slot. Falls
   * back to the first services when none are flagged (that is the backend's
   * existing selection behaviour). Never invents content.
   */
  const cards = useMemo<HubCard[]>(() => {
    const all = data ?? [];
    const flagged = all
      .filter((s) => Number.isInteger(s.hubSlot))
      .sort((a, b) => (a.hubSlot ?? 99) - (b.hubSlot ?? 99))
      .slice(0, 5);
    const chosen = flagged.length > 0 ? flagged : all.slice(0, 5);
    return chosen.map((service, index) => ({
      service,
      piece: HUB_SLOT_PIECES[index] ?? "top",
      slot: index,
    }));
  }, [data]);

  /* Off-screen pause — set as an attribute so no React render is triggered. */
  const setHubRef = useCallback((node: HTMLDivElement | null) => {
    hubRef.current = node;
    if (!node || typeof IntersectionObserver === "undefined") return;
    const observer = new IntersectionObserver(
      (entries) => {
        const entry = entries[0];
        node.classList.toggle("is-inview", Boolean(entry?.isIntersecting));
      },
      { rootMargin: "140px" },
    );
    observer.observe(node);
    // The observer disconnects when the node is replaced.
    return () => observer.disconnect();
  }, []);

  const onFocus = useCallback(() => setOpen(true), []);
  const onBlur = useCallback((event: React.FocusEvent<HTMLDivElement>) => {
    const next = event.relatedTarget as Node | null;
    if (!next || !event.currentTarget.contains(next)) setOpen(false);
    if (!next || !event.currentTarget.contains(next)) setActive(null);
  }, []);
  const onPointerEnter = useCallback((event: React.PointerEvent) => {
    if (event.pointerType === "mouse") setOpen(true);
  }, []);
  const onPointerLeave = useCallback((event: React.PointerEvent) => {
    if (event.pointerType === "mouse") {
      setOpen(false);
      setActive(null);
    }
  }, []);
  const onKeyDown = useCallback((event: React.KeyboardEvent) => {
    if (event.key !== "Escape") return;
    setOpen(false);
    setActive(null);
    const target = event.target as HTMLElement | null;
    target?.blur?.();
  }, []);
  const onTriggerClick = useCallback((event: React.MouseEvent) => {
    // Coarse pointers cannot hover, so a tap toggles instead.
    if (window.matchMedia("(pointer: coarse)").matches) {
      event.preventDefault();
      setOpen((value) => !value);
    }
  }, []);

  const clearActive = useCallback((event: React.FocusEvent | React.PointerEvent) => {
    const next = (event as React.FocusEvent).relatedTarget as Node | null;
    if (event.type === "blur" && next && event.currentTarget.contains(next)) return;
    setActive(null);
  }, []);

  const wireSlots = cards.length > 0 ? cards : [];

  return (
    <section id="hub" aria-labelledby="hub-heading" className="relative border-t border-line py-16 sm:py-24">
      <span aria-hidden="true" className="grid-crosshair hidden lg:block" style={{ left: 28, top: 40 }} />
      <CircuitTrace className="absolute right-0 top-8 hidden w-40 opacity-70 lg:block" />

      <div className="container-page">
        <Reveal variant="fade-in" className="max-w-2xl">
          <SectionIndex index="02" label="Hub" className="mb-4" />
          <p className="eyebrow">Our Services Hub</p>
          <h2 id="hub-heading" className="mt-3 text-h3 font-semibold">
            One mark, every discipline
          </h2>
          <span aria-hidden="true" className="heading-rule mt-4" />
          <p className="mt-4 text-sm leading-relaxed text-muted">
            The Jazari mark unfolds into the services we deliver. Hover, focus or tap the logo to
            explore each piece — and jump straight to the discipline you need.
          </p>
        </Reveal>

        <div
          ref={setHubRef}
          className={`hub${exploded ? " is-exploded" : ""}`}
          data-active={active ?? undefined}
          onFocus={onFocus}
          onBlur={onBlur}
          onPointerEnter={onPointerEnter}
          onPointerLeave={onPointerLeave}
          onKeyDown={onKeyDown}
        >
          <div
            className="hub__diagram"
            data-hub-grid={`${HUB_GRID_UNIT}:${HUB_DESIGN.width}:${HUB_DESIGN.height}`}
            data-hub-reference={HUB_REFERENCE_WIDTH}
          >
            {/* Circuit traces: logo piece → anchor node → orthogonal route → card socket. */}
            <svg
              className="hub__wires"
              viewBox={`0 0 ${HUB_DESIGN.width} ${HUB_DESIGN.height}`}
              preserveAspectRatio="none"
              aria-hidden="true"
              focusable="false"
            >
              {wireSlots.map((card) => (
                <path
                  key={card.piece}
                  className={`hub-wire${active === card.piece ? " is-lit" : ""}`}
                  data-hub-connector={card.piece}
                  d={wirePath(card.piece)}
                  vectorEffect="non-scaling-stroke"
                />
              ))}
              {wireSlots.map((card) => {
                const anchor = HUB_PIECES[card.piece].anchor;
                return (
                  <circle
                    key={`${card.piece}-node`}
                    className={`hub-wire__node${active === card.piece ? " is-lit" : ""}`}
                    data-hub-connector-node={card.piece}
                    cx={anchor.x}
                    cy={anchor.y}
                    r="3.4"
                    vectorEffect="non-scaling-stroke"
                  />
                );
              })}
            </svg>

            <div className="hub__stage">
              <button
                type="button"
                className="hub__trigger"
                aria-expanded={exploded}
                aria-controls="hub-service-list"
                onClick={onTriggerClick}
              >
                <span className="sr-only">
                  {exploded ? "Collapse the Jazari services logo" : "Explode the Jazari services logo"}
                </span>
                <svg
                  className="hub__logo"
                  viewBox={LOGO_VIEWBOX}
                  aria-hidden="true"
                  focusable="false"
                  /*
                   * Highlight is cleared when the pointer leaves the whole mark,
                   * not when it leaves an individual piece: exploding moves every
                   * piece 40-150 units, so a per-piece `pointerleave` fires the
                   * instant the animation starts and the card/trace highlight
                   * would blink off while the pointer is still on the logo.
                   */
                  onPointerLeave={() => setActive(null)}
                >
                  <defs>
                    {LOGO_PIECES.map((piece) => (
                      <linearGradient
                        key={piece.id}
                        id={logoGradientId(piece.id)}
                        gradientUnits="userSpaceOnUse"
                        x1={piece.gradient.x1}
                        y1={piece.gradient.y1}
                        x2={piece.gradient.x2}
                        y2={piece.gradient.y2}
                      >
                        {piece.gradient.stops.map((stop, index) => (
                          <stop key={index} offset={stop.offset} stopColor={stop.color} />
                        ))}
                      </linearGradient>
                    ))}
                  </defs>
                  {LOGO_PIECES.map((piece, index) => (
                    <g
                      key={piece.id}
                      data-logo-piece={piece.id}
                      className={active === piece.id ? "is-lit" : undefined}
                      style={pieceVars(piece.id, index)}
                      onPointerEnter={() => setActive(piece.id)}
                    >
                      <path d={piece.d} fill={`url(#${logoGradientId(piece.id)})`} />
                    </g>
                  ))}
                </svg>
              </button>
            </div>

            {/* Service list — ALWAYS in the DOM (no-JS + screen readers). */}
            <ul id="hub-service-list" className="hub__cards" aria-label="Services featured in the hub">
              {cards.map((card) => {
                const { service, piece, slot } = card;
                const Icon = iconRegistry[service.icon as IconName] ?? InfoIcon;
                const spec = HUB_PIECES[piece];
                return (
                  <li
                    key={service._id}
                    className="hub-card-slot"
                    data-hub-slot={slot}
                    data-hub-piece={piece}
                    style={cardSlotStyle(piece)}
                  >
                    <a
                      href={`#service-${service.slug}`}
                      className={`hub-card card card-ticks${active === piece ? " is-lit" : ""}`}
                      data-hub-card={piece}
                      data-side={spec.side}
                      onPointerEnter={() => setActive(piece)}
                      onPointerLeave={clearActive}
                      onFocus={() => setActive(piece)}
                      onBlur={clearActive}
                    >
                      <span className="hub-card__head">
                        <span className="hub-card__num" aria-hidden="true">
                          {String(slot + 1).padStart(2, "0")}
                        </span>
                        <span className="hub-card__icon" aria-hidden="true">
                          <Icon size={18} />
                        </span>
                      </span>
                      <span className="hub-card__title">{service.hubLabel || service.title}</span>
                      <span className="hub-card__desc">{service.description}</span>
                      <span className="hub-card__foot" aria-hidden="true">
                        <span className="hub-card__led" />
                        <span className="hub-card__explore">Explore →</span>
                      </span>
                      <span className="hub-card__socket" aria-hidden="true" />
                    </a>
                  </li>
                );
              })}
            </ul>
          </div>

          {cards.length === 0 && (
            <p className="hub__empty">
              Our service catalogue is being updated — the services below are the full, current list.
            </p>
          )}

          <p className="hub__hint" aria-hidden="true">
            <span className="hub__hint-desktop">Hover or focus the logo</span>
            <span className="hub__hint-touch">Tap the logo</span>
          </p>
        </div>
      </div>
    </section>
  );
}

export default ServicesHub;
