/**
 * The Jazari logo in 3D — built from the REAL traced artwork, not a hand-drawn
 * approximation.
 *
 * Source of truth: `components/services/logoGeometry.ts` (generated by
 * `npm run trace:logo` from `public/Main Logo.png`; measured silhouette IoU
 * 0.99839). The five real pieces — TOP BAND, RIGHT BAND, BOTTOM BAND, RIGHT
 * FOLD and the GREEN LEAF — are loaded with `THREE.SVGLoader`, extruded with a
 * soft bevel and kept as separate, addressable meshes so they can assemble,
 * idle, hover and explode independently.
 *
 * The real gradients are preserved in 3D: every vertex is coloured from the
 * artwork-sampled gradient stops (`userSpaceOnUse` axis), so the light-blue
 * caps, the deep-navy folds and the vivid green leaf survive instead of being
 * flattened to a single pastel tint.
 *
 * ORIENTATION: SVG coordinates are y-down; the whole group is rotated by π
 * around X so the assembled mark reads upright in the scene (leaf top-right).
 *
 * TUNING: the constants below control the assembled size and extrusion depth.
 * Colours come from `logoGeometry.ts`; materials from `materials.ts`.
 */

import {
  BufferAttribute,
  Color,
  ExtrudeGeometry,
  Group,
  Mesh,
  Vector3,
} from "three";
import { SVGLoader } from "three/examples/jsm/loaders/SVGLoader.js";
import { LOGO_PIECES, type LogoGradient, type LogoPiece } from "@/components/services/logoGeometry";
import { createLogoMaterial, type MaterialTier } from "./materials";
import { disposeObject } from "./helpers/disposeScene";

/* ---- Assembled logo parameters (TUNING) ---------------------------------- */
export const SOURCE_CENTER = 2048; // centre of the 4096 viewBox
const TARGET_SIZE = 3.05; // assembled logo longest axis, scene units
const EXTRUDE_DEPTH = 190; // source px — scaled down with the geometry
const BEVEL = 20; // source px — soft moulded edge
const FLY_IN = 2.1; // assembly start offset (scene units)

export interface LogoPieceSpec {
  /** Stable id (matches the real piece id). */
  id: string;
  color: string;
  /** Target (assembled) rotation around Z — always 0 for the real logo. */
  targetRotationZ: number;
  /** Assembly start skew. */
  startRotationZ: number;
  startPosition: Vector3;
}

export interface JazariRibbon {
  /** Parent group — engine positions/scales this; pieces stay local. */
  group: Group;
  /** The five real pieces (top, right, bottom, fold, leaf). */
  pieces: Mesh[];
  /** Green leaf (also the hotspot anchor). */
  leaf: Mesh;
  specs: LogoPieceSpec[];
  /** World-space hotspot anchor (the leaf, top-right of the mark). */
  anchor: Mesh;
  /**
   * Uniform scale applied to every piece (source px → scene units). Exposed so
   * the shatter field can map sampled silhouette points onto the exact same
   * coordinates as the solid pieces.
   */
  readonly scale: number;
  dispose(): void;
}

/** One `<path>` per real piece, in LOGO_PIECES order. */
function buildSvg(): string {
  const paths = LOGO_PIECES.map((piece) => `<path d="${piece.d}" fill="#ffffff"/>`).join("");
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 4096 4096">${paths}</svg>`;
}

/**
 * Sample a real logo gradient at a source-space point — the exact same math as
 * the per-vertex colouring below, reused by the shatter field so shards carry
 * the true artwork colours (light-blue caps, deep-navy folds, green leaf).
 */
export function sampleLogoGradient(gradient: LogoGradient, x: number, y: number): Color {
  const dx = gradient.x2 - gradient.x1;
  const dy = gradient.y2 - gradient.y1;
  const lengthSq = dx * dx + dy * dy || 1;
  return makeGradientSampler(gradient)(((x - gradient.x1) * dx + (y - gradient.y1) * dy) / lengthSq);
}

/** Per-vertex color sampler over a real logo gradient (linear interpolation). */
function makeGradientSampler(gradient: LogoGradient): (t: number) => Color {
  const colors = gradient.stops.map((stop) => new Color(stop.color));
  const scratch = new Color();
  return (t: number): Color => {
    const value = t < 0 ? 0 : t > 1 ? 1 : t;
    let i = 0;
    while (i < gradient.stops.length - 2 && value > gradient.stops[i + 1].offset) i += 1;
    const a = gradient.stops[i].offset;
    const b = gradient.stops[i + 1].offset;
    const local = b - a === 0 ? 0 : (value - a) / (b - a);
    const clampedLocal = local < 0 ? 0 : local > 1 ? 1 : local;
    return scratch.copy(colors[i]).lerp(colors[i + 1], clampedLocal);
  };
}

/** Colour every vertex from the real gradient axis (source pixel coords). */
function applyGradient(geometry: ExtrudeGeometry, gradient: LogoGradient): Color {
  const position = geometry.getAttribute("position");
  const dx = gradient.x2 - gradient.x1;
  const dy = gradient.y2 - gradient.y1;
  const lengthSq = dx * dx + dy * dy || 1;
  const sample = makeGradientSampler(gradient);
  const colors = new Float32Array(position.count * 3);

  for (let i = 0; i < position.count; i += 1) {
    const t =
      ((position.getX(i) - gradient.x1) * dx + (position.getY(i) - gradient.y1) * dy) / lengthSq;
    const color = sample(t);
    colors[i * 3] = color.r;
    colors[i * 3 + 1] = color.g;
    colors[i * 3 + 2] = color.b;
  }
  geometry.setAttribute("color", new BufferAttribute(colors, 3));

  // Representative colour for emissive/hover feedback (mid-gradient).
  return sample(0.5).clone();
}

interface BuiltPiece {
  piece: LogoPiece;
  geometry: ExtrudeGeometry;
  center: Vector3;
  emissive: Color;
}

export function createJazariRibbon(tier: MaterialTier): JazariRibbon {
  const group = new Group();
  group.name = "jazari-logo";
  group.rotation.x = Math.PI; // SVG y-down → scene y-up

  const parsed = new SVGLoader().parse(buildSvg());
  if (parsed.paths.length !== LOGO_PIECES.length) {
    throw new Error(
      `Jazari logo: expected ${LOGO_PIECES.length} traced pieces, SVGLoader produced ${parsed.paths.length}.`,
    );
  }

  // 1) Build every piece in source coordinates and colour it.
  const built: BuiltPiece[] = LOGO_PIECES.map((piece, index) => {
    const shapes = parsed.paths[index].toShapes();
    const geometry = new ExtrudeGeometry(shapes, {
      depth: EXTRUDE_DEPTH,
      bevelEnabled: true,
      bevelThickness: BEVEL,
      bevelSize: BEVEL,
      bevelSegments: 3,
      curveSegments: 6,
    });
    const emissive = applyGradient(geometry, piece.gradient);
    geometry.computeBoundingBox();
    const center = geometry.boundingBox
      ? geometry.boundingBox.getCenter(new Vector3())
      : new Vector3();
    return { piece, geometry, center, emissive };
  });

  // 2) Uniform scale so the assembled mark's longest axis equals TARGET_SIZE.
  let sizeX = 0;
  let sizeY = 0;
  for (const item of built) {
    const box = item.geometry.boundingBox;
    if (!box) continue;
    sizeX = Math.max(sizeX, box.max.x - box.min.x);
    sizeY = Math.max(sizeY, box.max.y - box.min.y);
  }
  const scale = TARGET_SIZE / Math.max(sizeX, sizeY, 1);

  // 3) Centre each geometry, scale it, and place it relative to the mark centre.
  const pieces: Mesh[] = [];
  const specs: LogoPieceSpec[] = [];
  let leafMesh: Mesh | null = null;

  for (const item of built) {
    item.geometry.translate(-item.center.x, -item.center.y, -EXTRUDE_DEPTH / 2);
    item.geometry.scale(scale, scale, scale);

    const mesh = new Mesh(item.geometry, createLogoMaterial(item.emissive, tier));
    mesh.name = `logo-${item.piece.id}`;
    mesh.userData.logoPiece = item.piece.id;
    mesh.position.set(
      (item.center.x - SOURCE_CENTER) * scale,
      (item.center.y - SOURCE_CENTER) * scale,
      0,
    );

    // Assembly start: pushed radially out from the mark centre + a small skew.
    const dir = new Vector3(mesh.position.x, mesh.position.y, 0);
    if (dir.lengthSq() < 1e-6) dir.set(0, 1, 0);
    dir.normalize();
    const startPosition = new Vector3(
      mesh.position.x + dir.x * FLY_IN,
      mesh.position.y + dir.y * FLY_IN,
      (pieces.length % 2 ? -1 : 1) * 1.1,
    );

    group.add(mesh);
    pieces.push(mesh);
    specs.push({
      id: item.piece.id,
      color: `#${item.emissive.getHexString()}`,
      targetRotationZ: 0,
      startRotationZ: (pieces.length % 2 ? 1 : -1) * 0.55,
      startPosition,
    });

    if (item.piece.id === "leaf") leafMesh = mesh;
  }

  const leaf = leafMesh ?? pieces[pieces.length - 1];

  return {
    group,
    pieces,
    leaf,
    specs,
    anchor: leaf,
    scale,
    dispose(): void {
      // BufferGeometry disposal is idempotent; one traversal is sufficient.
      disposeObject(group);
    },
  };
}
