/**
 * Real logo fracture — a Voronoi exploded view of the ACTUAL traced Jazari mark.
 *
 * Source of truth: `components/services/logoGeometry.ts` (generated by
 * `npm run trace:logo`; every piece is a closed `M … L … Z` polyline of real
 * traced geometry — no primitives, no hand-drawn approximation).
 *
 * How a fragment is built (4096-unit source space, then scaled to the scene):
 *   1. Each piece is split into `fragmentCount` cells by a weighted Voronoi
 *      diagram: seeds are dart-thrown inside the piece (area-proportional
 *      allocation, deterministic RNG) and every cell is the piece intersected
 *      with the bisector half-planes of its seed.
 *   2. The piece polygon is ear-clipped into triangles once. A cell is the
 *      exact union of `cell ∩ triangle` over those triangles, so each cell is
 *      computed by clipping CONVEX triangles with half-planes (Sutherland–
 *      Hodgman) — exact for any concave piece, no polygon-union library.
 *   3. Cap triangles (front + back) plus the cell's boundary walls form a
 *      closed slab. A sub-polygon edge becomes a wall only when no other
 *      sub-polygon of the same fragment contains its midpoint (that is how an
 *      internal ear-cut diagonal is told apart from a real fracture face).
 *   4. One merged BufferGeometry, one draw call. Baked per-vertex attributes
 *      (rest centroid, artwork colour, drift direction, piece separation vector,
 *      wave delay, spin, edge flag) drive the whole animation in the vertex
 *      shader — no per-frame CPU work.
 *
 * Explosion stages (timeline lives in `shatterState.ts`):
 *   A separating   — fragments travel on their PIECE's separation vector, so the
 *                    five real parts read as an exploded diagram (cracks closed)
 *   B fracturing   — each fragment adds its OWN outward drift, cracks open
 *   C floating     — full drift + tumble + wobble
 *   D reassembling — the same curves run backwards with a magnetic settle
 *
 * Growth Green stays a micro accent: only the leaf's own gradient can colour a
 * fragment green. Fracture faces glow Technology Blue (`BRAND.blue`) alone.
 *
 * TUNING: constants below.
 */

import {
  BufferAttribute,
  BufferGeometry,
  Color,
  DoubleSide,
  Mesh,
  ShapeUtils,
  ShaderMaterial,
  Vector2,
} from "three";
import { LOGO_PIECES, type LogoGradient, type LogoPiece } from "@/components/services/logoGeometry";
import { SOURCE_CENTER } from "./createLogoPieces";
import { SEPARATE_END } from "./shatterState";

/* ---- TUNING ------------------------------------------------------------- */

/** Slab depth in source px — matches the solid extrusion (190 + 2×20 bevel). */
export const FRAGMENT_DEPTH = 230;
/**
 * How far the fragments sit in FRONT of the solid mark, in source px. They
 * start exactly where the solid sits, so during the ~150 ms cross-fade they
 * would z-fight with it. The ribbon frame is rotated π about X, so "toward the
 * camera" is the negative local z.
 */
export const Z_BIAS = 16;
/** IoU raster resolution (source 4096 → RASTER). */
const RASTER = 512;
/** Skip degenerate cells smaller than this (source px²). */
const MIN_CELL_AREA = 48;
/** Dart-throw attempts per seed before the packing relaxes. */
const ATTEMPTS_PER_SEED = 240;
/** Tolerance (px²) for "this edge is shared with another sub-polygon". */
const SHARED_EPS = 1e-3;
/** Stage-A separation distance in scene units (piece → piece gap). */
const SEPARATE_DISTANCE = 0.085;
/** Full explosion drift in scene units (stage C). */
const DRIFT_DISTANCE = 1.05;

/* ---- Deterministic RNG (identical fracture on every reload) -------------- */

function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/* ---- Geometry primitives (source space) --------------------------------- */

/** Parse a traced `M … L … Z` polyline. Curves would mean the trace regressed. */
function parsePolyline(d: string): Vector2[] {
  if (/[CQAS]/i.test(d)) {
    throw new Error("Jazari fracture: traced piece contains curves; expected M/L/Z polylines.");
  }
  const tokens = d.match(/[MLZ]|-?\d*\.?\d+/gi) ?? [];
  const points: Vector2[] = [];
  let command = "";
  let i = 0;
  while (i < tokens.length) {
    const token = tokens[i];
    if (/^[MLZ]$/i.test(token)) {
      command = token.toUpperCase();
      i += 1;
      if (command === "Z") break;
      continue;
    }
    if (command === "M" || command === "L") {
      points.push(new Vector2(Number(tokens[i]), Number(tokens[i + 1])));
      i += 2;
    } else {
      i += 1;
    }
  }
  while (points.length > 3 && points[0].distanceToSquared(points[points.length - 1]) < 1e-6) {
    points.pop();
  }
  return points;
}

/** Signed area (shoelace); positive when counter-clockwise. */
function signedArea(poly: Vector2[]): number {
  let sum = 0;
  for (let i = 0, n = poly.length; i < n; i += 1) {
    const a = poly[i];
    const b = poly[(i + 1) % n];
    sum += a.x * b.y - b.x * a.y;
  }
  return sum / 2;
}

function ensureCcw(poly: Vector2[]): Vector2[] {
  return signedArea(poly) < 0 ? poly.slice().reverse() : poly;
}

/** Even-odd point-in-polygon (handles concave rings). */
function pointInPolygon(x: number, y: number, poly: Vector2[]): boolean {
  let inside = false;
  for (let i = 0, j = poly.length - 1; i < poly.length; j = i, i += 1) {
    const a = poly[i];
    const b = poly[j];
    if (a.y > y !== b.y > y && x < ((b.x - a.x) * (y - a.y)) / (b.y - a.y) + a.x) inside = !inside;
  }
  return inside;
}

interface Box {
  minX: number;
  minY: number;
  maxX: number;
  maxY: number;
}

function bboxOf(poly: Vector2[]): Box {
  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;
  for (const p of poly) {
    if (p.x < minX) minX = p.x;
    if (p.y < minY) minY = p.y;
    if (p.x > maxX) maxX = p.x;
    if (p.y > maxY) maxY = p.y;
  }
  return { minX, minY, maxX, maxY };
}

/** Area-weighted centroid + |area| of a simple polygon. */
function measure(poly: Vector2[]): { area: number; cx: number; cy: number } {
  let twice = 0;
  let cx = 0;
  let cy = 0;
  for (let i = 0, n = poly.length; i < n; i += 1) {
    const a = poly[i];
    const b = poly[(i + 1) % n];
    const cross = a.x * b.y - b.x * a.y;
    twice += cross;
    cx += (a.x + b.x) * cross;
    cy += (a.y + b.y) * cross;
  }
  if (Math.abs(twice) < 1e-9) {
    const box = bboxOf(poly);
    return { area: 0, cx: (box.minX + box.maxX) / 2, cy: (box.minY + box.maxY) / 2 };
  }
  return { area: twice / 2, cx: cx / (6 * twice), cy: cy / (6 * twice) };
}

/**
 * Sutherland–Hodgman clip of a CONVEX subject by the half-plane
 * `dot(p - m, n) <= 0`. Exact for convex subjects, which is all we ever clip.
 */
function clipHalfPlane(subject: Vector2[], m: Vector2, n: Vector2): Vector2[] {
  const out: Vector2[] = [];
  const total = subject.length;
  if (total === 0) return out;
  let px = subject[total - 1].x;
  let py = subject[total - 1].y;
  let dp = (px - m.x) * n.x + (py - m.y) * n.y;
  let insidePrev = dp <= 0;
  for (let i = 0; i < total; i += 1) {
    const cx = subject[i].x;
    const cy = subject[i].y;
    const dc = (cx - m.x) * n.x + (cy - m.y) * n.y;
    const insideNext = dc <= 0;
    if (insideNext !== insidePrev) {
      const t = dp / (dp - dc);
      out.push(new Vector2(px + (cx - px) * t, py + (cy - py) * t));
    }
    if (insideNext) out.push(new Vector2(cx, cy));
    px = cx;
    py = cy;
    dp = dc;
    insidePrev = insideNext;
  }
  return out;
}

/** True when `p` is inside (or on) the CCW convex polygon, within `SHARED_EPS`. */
function insideConvex(p: Vector2, poly: Vector2[]): boolean {
  for (let i = 0, n = poly.length; i < n; i += 1) {
    const a = poly[i];
    const b = poly[(i + 1) % n];
    const cross = (b.x - a.x) * (p.y - a.y) - (b.y - a.y) * (p.x - a.x);
    if (cross < -SHARED_EPS) return false;
  }
  return true;
}

/* ---- Regions: one per traced piece contour ------------------------------ */

interface Region {
  piece: LogoPiece;
  /** CCW outline, no repeated closing point. */
  poly: Vector2[];
  area: number;
  cx: number;
  cy: number;
  box: Box;
  /** Ear-clipped triangles (index triples into `poly`). */
  tris: number[][];
  /** Artwork gradient sampler in display-referred (sRGB) values. */
  sample: (x: number, y: number) => { r: number; g: number; b: number };
}

/**
 * One sampler per region: gradient stops stay in the linear working space and
 * are interpolated once per vertex. The shader ends with three's
 * `<tonemapping_fragment>` + `<colorspace_fragment>` chunks, so the fragment
 * is tone-mapped and encoded exactly like the solid mark it replaces — that is
 * what makes the stage-A hand-off seamless.
 */
function makeSampler(gradient: LogoGradient): (x: number, y: number) => { r: number; g: number; b: number } {
  const stops = gradient.stops.map((stop) => {
    const color = new Color(stop.color);
    return { offset: stop.offset, r: color.r, g: color.g, b: color.b };
  });
  const dx = gradient.x2 - gradient.x1;
  const dy = gradient.y2 - gradient.y1;
  const lengthSq = dx * dx + dy * dy || 1;
  return (x: number, y: number) => {
    let t = ((x - gradient.x1) * dx + (y - gradient.y1) * dy) / lengthSq;
    t = t < 0 ? 0 : t > 1 ? 1 : t;
    let i = 0;
    while (i < stops.length - 2 && t > stops[i + 1].offset) i += 1;
    const a = stops[i];
    const b = stops[i + 1];
    const span = b.offset - a.offset;
    const local = span === 0 ? 0 : Math.min(1, Math.max(0, (t - a.offset) / span));
    return {
      r: a.r + (b.r - a.r) * local,
      g: a.g + (b.g - a.g) * local,
      b: a.b + (b.b - a.b) * local,
    };
  };
}

function buildRegions(): Region[] {
  const regions: Region[] = [];
  for (const piece of LOGO_PIECES) {
    const raw = parsePolyline(piece.d);
    if (raw.length < 3) continue;
    const poly = ensureCcw(raw);
    const { area, cx, cy } = measure(poly);
    if (area <= 0) continue;
    const box = bboxOf(poly);
    box.minX -= 1;
    box.minY -= 1;
    box.maxX += 1;
    box.maxY += 1;
    regions.push({
      piece,
      poly,
      area,
      cx,
      cy,
      box,
      tris: ShapeUtils.triangulateShape(poly, []).map((face) => face.slice()),
      sample: makeSampler(piece.gradient),
    });
  }
  return regions;
}

/** Area-proportional seed counts; every contour keeps at least one fragment. */
function allocateCounts(regions: Region[], total: number): number[] {
  const counts = regions.map(() => 1);
  const areaSum = regions.reduce((sum, region) => sum + region.area, 0) || 1;
  let remaining = Math.max(0, total - regions.length);
  while (remaining > 0) {
    let best = 0;
    let bestScore = -Infinity;
    for (let i = 0; i < regions.length; i += 1) {
      const score = (total * regions[i].area) / areaSum - counts[i];
      if (score > bestScore) {
        bestScore = score;
        best = i;
      }
    }
    counts[best] += 1;
    remaining -= 1;
  }
  return counts;
}

/** Deterministic dart-throwing with a relaxing minimum distance. */
function scatterSeeds(region: Region, count: number, rand: () => number): Vector2[] {
  const seeds: Vector2[] = [];
  const width = region.box.maxX - region.box.minX;
  const height = region.box.maxY - region.box.minY;
  let minDist = Math.sqrt(region.area / count) * 0.8;
  const budget = ATTEMPTS_PER_SEED * count;
  let attempts = 0;
  while (seeds.length < count && attempts < budget) {
    attempts += 1;
    if (attempts % ATTEMPTS_PER_SEED === 0) minDist *= 0.92;
    const x = region.box.minX + rand() * width;
    const y = region.box.minY + rand() * height;
    if (!pointInPolygon(x, y, region.poly)) continue;
    let clear = true;
    for (const seed of seeds) {
      const dx = seed.x - x;
      const dy = seed.y - y;
      if (dx * dx + dy * dy < minDist * minDist) {
        clear = false;
        break;
      }
    }
    if (clear) seeds.push(new Vector2(x, y));
  }
  // Never under-deliver: fill the remainder with plain interior points.
  let guard = 0;
  while (seeds.length < count && guard < budget * 2) {
    guard += 1;
    const x = region.box.minX + rand() * width;
    const y = region.box.minY + rand() * height;
    if (pointInPolygon(x, y, region.poly)) seeds.push(new Vector2(x, y));
  }
  return seeds;
}

/* ---- Shaders ------------------------------------------------------------ */

const FRAGMENT_VERTEX = /* glsl */ `
  attribute vec3 aCenter;
  attribute vec3 aColor;
  attribute vec3 aDir;
  attribute vec3 aSep;
  attribute float aDelay;
  attribute float aSpin;
  attribute float aEdge;

  uniform float uProgress;
  uniform float uTime;
  uniform float uDrift;
  uniform float uSep;
  uniform float uMagnetic;
  uniform float uSeparateEnd;

  varying vec3 vColor;
  varying vec3 vNormalV;
  varying vec3 vViewPos;
  varying float vEdge;

  mat3 axisRotate(vec3 axis, float angle) {
    float c = cos(angle);
    float s = sin(angle);
    float t = 1.0 - c;
    return mat3(
      t * axis.x * axis.x + c,            t * axis.x * axis.y - s * axis.z, t * axis.x * axis.z + s * axis.y,
      t * axis.x * axis.y + s * axis.z,   t * axis.y * axis.y + c,          t * axis.y * axis.z - s * axis.x,
      t * axis.x * axis.z - s * axis.y,   t * axis.y * axis.z + s * axis.x, t * axis.z * axis.z + c
    );
  }

  float easeForward(float t) { return t * t * (3.0 - 2.0 * t); }

  /* Magnetic settle: the return runs a back-ease, so a fragment sails a few
     percent past home and springs back instead of parking dead. */
  float easeReturn(float t) { float u = t - 1.0; return 1.0 + 2.0 * u * u * u + u * u; }

  void main() {
    float sepT = clamp(uProgress / uSeparateEnd, 0.0, 1.0);
    float fracT = clamp((uProgress - uSeparateEnd) / (1.0 - uSeparateEnd), 0.0, 1.0);
    float sep = easeForward(sepT);
    float frac = easeForward(fracT);

    if (uMagnetic > 0.5) {
      sep = 1.0 - easeReturn(1.0 - sep);
      frac = 1.0 - easeReturn(1.0 - frac);
    }

    vec3 center = aCenter + aSep * (sep * uSep) + aDir * (frac * uDrift * (1.0 + aSpin * 0.12));

    // Floating wobble — stage C only, so stages A/B stay a clean diagram.
    float floatMix = clamp(frac, 0.0, 1.0);
    center += vec3(
      sin(uTime * 0.85 + aDelay * 11.0),
      cos(uTime * 0.7 + aSpin * 7.0),
      sin(uTime * 0.6 + aDelay * 5.0)
    ) * (0.03 * floatMix * uDrift);

    vec3 axis = normalize(vec3(aDir.y, -aDir.x, 0.42) + vec3(0.0001));
    float angle = (aSpin * 1.7 + uTime * 0.45 * aSpin) * floatMix + aSpin * 0.14 * sep;
    mat3 rot = axisRotate(axis, angle);

    vec3 transformed = center + rot * (position - aCenter);
    vec4 mvPosition = modelViewMatrix * vec4(transformed, 1.0);
    vViewPos = mvPosition.xyz;
    vNormalV = normalize(mat3(modelViewMatrix) * (rot * normal));
    vColor = aColor;
    vEdge = aEdge;
    gl_Position = projectionMatrix * mvPosition;
  }
`;

const FRAGMENT_FRAGMENT = /* glsl */ `
  uniform float uGlow;
  uniform vec3 uNeon;

  varying vec3 vColor;
  varying vec3 vNormalV;
  varying vec3 vViewPos;
  varying float vEdge;

  void main() {
    vec3 n = normalize(vNormalV);
    vec3 v = normalize(-vViewPos);
    float fres = pow(1.0 - clamp(abs(dot(n, v)), 0.0, 1.0), 2.2);
    vec3 lightDir = normalize(vec3(0.34, 0.5, 0.79));
    float ndl = clamp(dot(n, lightDir) * 0.5 + 0.5, 0.0, 1.0);

    // Caps keep the artwork gradient (Growth Green only on the leaf).
    vec3 cap = vColor * (0.72 + 0.52 * ndl) + uNeon * 0.2 * fres;
    // Fracture faces glow Technology Blue — the neon edge of the break.
    vec3 wall = uNeon * (0.75 + 0.45 * fres) * uGlow;

    vec3 col = mix(cap, wall, step(0.5, vEdge));
    gl_FragColor = vec4(col, 1.0);
    #include <tonemapping_fragment>
    #include <colorspace_fragment>
  }
`;

/* ---- Public API --------------------------------------------------------- */

export interface FractureMetrics {
  /** Raster IoU of the tiled fracture vs. the traced logo silhouette (≥ 0.95). */
  iou: number;
  /** (Σ fragment area − union area) / union area — 0 is a perfect tiling. */
  overlapRatio: number;
  /** Median fragment bbox width ÷ logo bbox width, in local units. */
  medianWidthRatio: number;
  /** Smallest / largest fragment area (source px²) — budget diagnostics. */
  minArea: number;
  maxArea: number;
  /** Per traced contour: analytic area, area actually fractured, and the ratio. */
  pieces: Array<{ id: string; area: number; fractured: number; ratio: number }>;
}

export interface FractureField {
  /** Single merged mesh (one draw call) — parent it to the logo's frame. */
  mesh: Mesh;
  /** Number of Voronoi fragments actually built. */
  readonly count: number;
  /** Per-fragment rest bbox (minX, maxX, minY, maxY) in scene units. */
  readonly restBoxes: Float32Array;
  setProgress(progress: number): void;
  setMagnetic(value: boolean): void;
  setTime(time: number): void;
  setGlow(glow: number): void;
  /** Test hook: hide/show the fragments (screenshot A/B isolation). */
  setVisible(visible: boolean): void;
  /** Measured once on demand (raster work), then cached. */
  metrics(): FractureMetrics;
  dispose(): void;
}

/**
 * Build the fracture. Returns `null` when it cannot be built (no DOM during
 * SSR, or the trace produced no usable contour) so the engine can fall back to
 * the dust layer alone.
 */
export function createFracture(
  count: number,
  logoScale: number,
  glow: number,
  neon: string,
): FractureField | null {
  if (count <= 0 || typeof document === "undefined") return null;

  const regions = buildRegions();
  if (regions.length === 0) return null;    const budgets = allocateCounts(regions, count);
  const rand = mulberry32(0x2f6d21b3);

  const position: number[] = [];
  const color: number[] = [];
  const center: number[] = [];
  const dir: number[] = [];
  const sep: number[] = [];
  const delay: number[] = [];
  const spin: number[] = [];
  const edge: number[] = [];

  const rings: Vector2[][] = [];
  const fragmentAreas: number[] = [];
  const pieceStats: Array<{ id: string; area: number; fractured: number }> = [];
  const restBoxes: number[] = [];
  const halfDepth = (FRAGMENT_DEPTH / 2) * logoScale;
  const zBias = -Z_BIAS * logoScale; // ribbon frame is flipped: -z faces the camera
  let built = 0;
  let logoMinX = Infinity;
  let logoMaxX = -Infinity;

  for (let r = 0; r < regions.length; r += 1) {
    const region = regions[r];
    pieceStats.push({ id: region.piece.id, area: region.area, fractured: 0 });
    const seeds = scatterSeeds(region, budgets[r], rand);
    if (seeds.length < 1) continue;

    // Stage A separation: the whole contour travels as one exploded part.
    const pieceRadius = Math.hypot(region.cx - SOURCE_CENTER, region.cy - SOURCE_CENTER) || 1;
    const sepX = ((region.cx - SOURCE_CENTER) / pieceRadius) * 62;
    const sepY = ((region.cy - SOURCE_CENTER) / pieceRadius) * 62;
    const sepZ = (r % 2 === 0 ? 1 : -1) * 96;

    // Bisector half-planes for every seed of this contour.
    const planes = seeds.map((seed, index) => {
      const list: Array<{ m: Vector2; n: Vector2 }> = [];
      for (let j = 0; j < seeds.length; j += 1) {
        if (j === index) continue;
        const other = seeds[j];
        const dx = other.x - seed.x;
        const dy = other.y - seed.y;
        const len = Math.hypot(dx, dy);
        if (len < 1e-6) continue;
        list.push({
          m: new Vector2((seed.x + other.x) / 2, (seed.y + other.y) / 2),
          n: new Vector2(dx / len, dy / len),
        });
      }
      return list;
    });

    for (let i = 0; i < seeds.length; i += 1) {
      const cellPlanes = planes[i];

      // Conservative cell box: the contour box clipped by every bisector.
      let boxPoly: Vector2[] = [
        new Vector2(region.box.minX, region.box.minY),
        new Vector2(region.box.maxX, region.box.minY),
        new Vector2(region.box.maxX, region.box.maxY),
        new Vector2(region.box.minX, region.box.maxY),
      ];
      for (const plane of cellPlanes) {
        boxPoly = clipHalfPlane(boxPoly, plane.m, plane.n);
        if (boxPoly.length < 3) break;
      }
      if (boxPoly.length < 3) continue;
      const cellBox = bboxOf(boxPoly);

      // cell ∩ contour = union over the contour's triangles of cell ∩ triangle.
      const subPolys: Vector2[][] = [];
      for (const tri of region.tris) {
        const a = region.poly[tri[0]];
        const b = region.poly[tri[1]];
        const c = region.poly[tri[2]];
        if (!a || !b || !c) continue;
        if (
          Math.max(a.x, b.x, c.x) < cellBox.minX ||
          Math.min(a.x, b.x, c.x) > cellBox.maxX ||
          Math.max(a.y, b.y, c.y) < cellBox.minY ||
          Math.min(a.y, b.y, c.y) > cellBox.maxY
        ) {
          continue;
        }
        let clipped: Vector2[] = [a.clone(), b.clone(), c.clone()];
        for (const plane of cellPlanes) {
          clipped = clipHalfPlane(clipped, plane.m, plane.n);
          if (clipped.length < 3) break;
        }
        if (clipped.length < 3) continue;
        const area = signedArea(clipped);
        if (Math.abs(area) < 1e-9) continue;
        subPolys.push(area < 0 ? clipped.reverse() : clipped);
      }
      if (subPolys.length === 0) continue;

      // Fragment centroid, area and rest bbox (source space).
      let fragArea = 0;
      let fcx = 0;
      let fcy = 0;
      let minX = Infinity;
      let minY = Infinity;
      let maxX = -Infinity;
      let maxY = -Infinity;
      for (const poly of subPolys) {
        const { area, cx, cy } = measure(poly);
        const magnitude = Math.abs(area);
        fragArea += magnitude;
        fcx += cx * magnitude;
        fcy += cy * magnitude;
        for (const p of poly) {
          if (p.x < minX) minX = p.x;
          if (p.y < minY) minY = p.y;
          if (p.x > maxX) maxX = p.x;
          if (p.y > maxY) maxY = p.y;
        }
      }
      if (fragArea < MIN_CELL_AREA) continue;
      fcx /= fragArea;
      fcy /= fragArea;

      const centerX = (fcx - SOURCE_CENTER) * logoScale;
      const centerY = (fcy - SOURCE_CENTER) * logoScale;
      const centerZ = zBias;

      // Drift: radial from the mark centre with a gentle depth lift.
      const radius = Math.hypot(fcx - SOURCE_CENTER, fcy - SOURCE_CENTER) || 1;
      const jitter = (rand() - 0.5) * 0.42;
      const dirX = (fcx - SOURCE_CENTER) / radius + jitter;
      const dirY = (fcy - SOURCE_CENTER) / radius + jitter * 0.6;
      const dirZ = 0.22 + rand() * 0.55;
      const dirLen = Math.hypot(dirX, dirY, dirZ) || 1;
      const delayValue = Math.min(0.6, (radius / 2900) * 0.55 + rand() * 0.2);
      const spinValue = (rand() - 0.5) * 2.2;

      const emit = (sourceX: number, sourceY: number, localZ: number, isEdge: number): void => {
        position.push(
          (sourceX - SOURCE_CENTER) * logoScale,
          (sourceY - SOURCE_CENTER) * logoScale,
          localZ,
        );
        const sample = region.sample(sourceX, sourceY);
        color.push(sample.r, sample.g, sample.b);
        center.push(centerX, centerY, centerZ);
        dir.push(dirX / dirLen, dirY / dirLen, dirZ / dirLen);
        sep.push(sepX, sepY, sepZ);
        delay.push(delayValue);
        spin.push(spinValue);
        edge.push(isEdge);
      };

      for (const poly of subPolys) {
        // Front + back caps (convex fan).
        for (let t = 1; t + 1 < poly.length; t += 1) {
          emit(poly[0].x, poly[0].y, zBias + halfDepth, 0);
          emit(poly[t].x, poly[t].y, zBias + halfDepth, 0);
          emit(poly[t + 1].x, poly[t + 1].y, zBias + halfDepth, 0);
          emit(poly[0].x, poly[0].y, zBias - halfDepth, 0);
          emit(poly[t + 1].x, poly[t + 1].y, zBias - halfDepth, 0);
          emit(poly[t].x, poly[t].y, zBias - halfDepth, 0);
        }
        // Walls: only edges no other sub-polygon of this fragment owns.
        for (let e = 0; e < poly.length; e += 1) {
          const a = poly[e];
          const b = poly[(e + 1) % poly.length];
          const mid = new Vector2((a.x + b.x) / 2, (a.y + b.y) / 2);
          let shared = false;
          for (const other of subPolys) {
            if (other === poly) continue;
            if (insideConvex(mid, other)) {
              shared = true;
              break;
            }
          }
          if (shared) continue;
          emit(a.x, a.y, zBias + halfDepth, 1);
          emit(b.x, b.y, zBias + halfDepth, 1);
          emit(b.x, b.y, zBias - halfDepth, 1);
          emit(a.x, a.y, zBias + halfDepth, 1);
          emit(b.x, b.y, zBias - halfDepth, 1);
          emit(a.x, a.y, zBias - halfDepth, 1);
        }
      }

      rings.push(...subPolys);
      fragmentAreas.push(fragArea);
      pieceStats[r].fractured += fragArea;
      restBoxes.push(
        (minX - SOURCE_CENTER) * logoScale,
        (maxX - SOURCE_CENTER) * logoScale,
        (minY - SOURCE_CENTER) * logoScale,
        (maxY - SOURCE_CENTER) * logoScale,
      );
      if (minX < logoMinX) logoMinX = minX;
      if (maxX > logoMaxX) logoMaxX = maxX;
      built += 1;
    }
  }

  if (built === 0) return null;

  const geometry = new BufferGeometry();
  geometry.setAttribute("position", new BufferAttribute(new Float32Array(position), 3));
  geometry.setAttribute("color", new BufferAttribute(new Float32Array(color), 3));
  geometry.setAttribute("aCenter", new BufferAttribute(new Float32Array(center), 3));
  geometry.setAttribute("aDir", new BufferAttribute(new Float32Array(dir), 3));
  geometry.setAttribute("aSep", new BufferAttribute(new Float32Array(sep), 3));
  geometry.setAttribute("aDelay", new BufferAttribute(new Float32Array(delay), 1));
  geometry.setAttribute("aSpin", new BufferAttribute(new Float32Array(spin), 1));
  geometry.setAttribute("aEdge", new BufferAttribute(new Float32Array(edge), 1));
  geometry.computeVertexNormals(); // flat normals — hard-edged fracture faces
  geometry.computeBoundingSphere();

  const material = new ShaderMaterial({
    vertexShader: FRAGMENT_VERTEX,
    fragmentShader: FRAGMENT_FRAGMENT,
    uniforms: {
      uProgress: { value: 0 },
      uTime: { value: 0 },
      uDrift: { value: DRIFT_DISTANCE },
      uSep: { value: SEPARATE_DISTANCE },
      uMagnetic: { value: 0 },
      uSeparateEnd: { value: SEPARATE_END },
      uGlow: { value: glow },
      uNeon: { value: neonRgb(neon) },
    },
    side: DoubleSide,
  });

  const mesh = new Mesh(geometry, material);
  mesh.name = "jazari-fragments";
  mesh.frustumCulled = false;
  mesh.userData.noPick = true; // decorative — never a hover target

  const logoWidth = Math.max((logoMaxX - logoMinX) * logoScale, 1e-6);
  const widths: number[] = [];
  for (let i = 0; i < restBoxes.length; i += 4) widths.push(restBoxes[i + 1] - restBoxes[i]);
  widths.sort((a, b) => a - b);
  const medianWidthRatio = widths.length > 0 ? widths[Math.floor(widths.length / 2)] / logoWidth : 0;

  let cached: FractureMetrics | null = null;
  let visibleEnabled = true;

  return {
    mesh,
    count: built,
    restBoxes: new Float32Array(restBoxes),
    setProgress(progress: number): void {
      material.uniforms.uProgress.value = progress;
      mesh.visible = visibleEnabled && progress > 0.002;
    },
    setMagnetic(value: boolean): void {
      material.uniforms.uMagnetic.value = value ? 1 : 0;
    },
    setTime(time: number): void {
      material.uniforms.uTime.value = time;
    },
    setGlow(next: number): void {
      material.uniforms.uGlow.value = next;
    },
    setVisible(visible: boolean): void {
      visibleEnabled = visible;
      mesh.visible = visible && material.uniforms.uProgress.value > 0.002;
    },
    metrics(): FractureMetrics {
      if (cached) return cached;
      const raster = rasterize(regions, rings);
      const unionArea = fragmentAreas.reduce((sum, value) => sum + value, 0);
      cached = {
        iou: raster.iou,
        overlapRatio: raster.union > 0 ? Math.max(0, (unionArea - raster.union) / raster.union) : 1,
        medianWidthRatio,
        minArea: fragmentAreas.length ? Math.min(...fragmentAreas) : 0,
        maxArea: fragmentAreas.length ? Math.max(...fragmentAreas) : 0,
        pieces: pieceStats.map((piece) => ({
          ...piece,
          ratio: piece.area > 0 ? piece.fractured / piece.area : 0,
        })),
      };
      return cached;
    },
    dispose(): void {
      geometry.dispose();
      material.dispose();
    },
  };
}

/**
 * Linear-working-space components of a hex colour: the shader's tail chunks do
 * tone mapping + output encoding, so uniforms must be linear like everything
 * else in the scene.
 */
function neonRgb(hex: string): [number, number, number] {
  const color = new Color(hex);
  return [color.r, color.g, color.b];
}

/* ---- Silhouette verification -------------------------------------------- */

/** Rasterise silhouette vs. fracture, then measure IoU + union area (px²). */
function rasterize(regions: Region[], rings: Vector2[][]): { iou: number; union: number } {
  const scale = RASTER / 4096;
  const canvas = document.createElement("canvas");
  canvas.width = RASTER;
  canvas.height = RASTER;
  const ctx = canvas.getContext("2d", { willReadFrequently: true });
  if (!ctx) return { iou: 0, union: 0 };

  const trace = (ctx2d: CanvasRenderingContext2D, poly: Vector2[]): void => {
    // moveTo per ring: without it every ring would be joined to the previous
    // one by a stray edge, and nonzero fill would cancel whole regions.
    ctx2d.moveTo(poly[0].x, poly[0].y);
    for (let i = 1; i < poly.length; i += 1) ctx2d.lineTo(poly[i].x, poly[i].y);
    ctx2d.closePath();
  };

  const maskOf = (paint: (ctx2d: CanvasRenderingContext2D) => void): Uint8Array => {
    ctx.setTransform(1, 0, 0, 1, 0, 0);
    ctx.clearRect(0, 0, RASTER, RASTER);
    ctx.setTransform(scale, 0, 0, scale, 0, 0);
    ctx.fillStyle = "#ffffff";
    paint(ctx);
    ctx.fill();
    ctx.setTransform(1, 0, 0, 1, 0, 0);
    const data = ctx.getImageData(0, 0, RASTER, RASTER).data;
    const mask = new Uint8Array(RASTER * RASTER);
    for (let p = 0; p < RASTER * RASTER; p += 1) mask[p] = data[p * 4 + 3] > 128 ? 1 : 0;
    return mask;
  };

  const silhouette = maskOf((ctx2d) => {
    ctx2d.beginPath();
    for (const region of regions) trace(ctx2d, region.poly);
  });
  const fracture = maskOf((ctx2d) => {
    ctx2d.beginPath();
    for (const ring of rings) trace(ctx2d, ring);
  });

  const pixelArea = (4096 / RASTER) ** 2;
  let intersection = 0;
  let union = 0;
  for (let p = 0; p < RASTER * RASTER; p += 1) {
    const a = silhouette[p];
    const b = fracture[p];
    if (a || b) union += 1;
    if (a && b) intersection += 1;
  }
  canvas.width = 0;
  canvas.height = 0;
  return { iou: union > 0 ? intersection / union : 0, union: union * pixelArea };
}
